
services:

  db:
    image: postgis/postgis:15-3.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data

    environment:
      - POSTGRES_DB=trails
      - POSTGRES_USER=finder
      - POSTGRES_PASSWORD=auu_Auu!

  server:
    image: lusiolla/trailfinder:v0.1.1_alpha_2026-05-19
    ports:
      - "8080:8080"

    depends_on:
      - db

    environment:
      - DB_NAME=trails
      - POSTGRES_USER=finder
      - POSTGRES_PASSWORD=auu_Auu!
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data: