spring.sql.init.mode=always
#spring.batch.jdbc.initialize-schema=always

#spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/trails
#spring.datasource.username=finder
#spring.datasource.password=auu_Auu!
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver