DROP TABLE IF EXISTS trails CASCADE;

DROP TABLE IF EXISTS types CASCADE;

DROP TABLE IF EXISTS complexity CASCADE;

DROP TABLE IF EXISTS points CASCADE;

DROP TABLE IF EXISTS points_of_trails CASCADE;

DROP TABLE IF EXISTS users CASCADE;


CREATE TABLE "trails" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255) NOT NULL,
  "type_id" bigint,
  "duration" timestamp NOT NULL,
  "complexity_id" bigint NOT NULL
);

CREATE TABLE "types" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE "complexity" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255)
);

CREATE TABLE "points" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "point" geometry
);

CREATE TABLE "points_of_trails" (
  "trail_id" bigint,
  "point_id" bigint,
  "point_number" int NOT NULL,
  PRIMARY KEY ("trail_id", "point_id")
);

CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255)
);

ALTER TABLE "trails" ADD FOREIGN KEY ("type_id") REFERENCES "types" ("id");

ALTER TABLE "trails" ADD FOREIGN KEY ("complexity_id") REFERENCES "complexity" ("id");

ALTER TABLE "points_of_trails" ADD FOREIGN KEY ("trail_id") REFERENCES "trails" ("id");

ALTER TABLE "points_of_trails" ADD FOREIGN KEY ("point_id") REFERENCES "points" ("id");