DROP TABLE IF EXISTS tracks CASCADE;

DROP TABLE IF EXISTS metadata CASCADE;

DROP TABLE IF EXISTS track_authors CASCADE;

DROP TABLE IF EXISTS track_links CASCADE;

DROP TABLE IF EXISTS users CASCADE;


CREATE TABLE "tracks" (
  "id" UUID PRIMARY KEY,
  "name" varchar(120) NOT NULL,
  "description" varchar (255),
  "type" varchar (120),
  "duration" time,
  "complexity" varchar(120),
  "points" geometry(LineStringZ, 4326) NOT NULL
);

CREATE TABLE "metadata" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "track_id" UUID,
  "name" varchar(120),
  "author_id" bigint,
  "link_id" bigint
);

CREATE TABLE "track_authors" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(120)
);

CREATE TABLE "track_links" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "url" varchar(120)
);

CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(120)
);

ALTER TABLE "metadata" ADD FOREIGN KEY ("author_id") REFERENCES "track_authors" ("id");
ALTER TABLE "metadata" ADD FOREIGN KEY ("link_id") REFERENCES "track_links" ("id");
ALTER TABLE "metadata" ADD FOREIGN KEY ("track_id") REFERENCES "tracks" ("id");
